[SAMBAD-157]-운영자 질문 및 답변 등록 api
depromeet/15th-team3-BE pull request #41
Opened 2024-07-26 16:09 UTC by LeeHanEum

### 📍 [SAMBAD-157]-운영자 질문 및 답변 등록 api 

## ✔️ PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## 📝 개요
- 모임의 질문이나 답변이 아닌, 운영자가 추가 등록하는 api 입니다.
- csv를 통한 등록인 ExcelSheetHandler 클래스를 추가하였습니다.

## 💡 코드 리뷰 시 참고 사항
- ExcelSheetHandler에서의 예외 처리를 어떻게 해야하면 더 개선할 수 있을지 알려주시면 감사하겠습니다.
- 해당 pr이 merge되고 난 후 csv 파일을 통한 읽기 pr을 올리도록 하겠습니다.

## 🔗 ISSUE 링크
- resolved [SAMBAD-이슈번호]()

2024-07-27 03:42 UTC, nahyeon99 requested changes
ExcelSheetHandler 이거 이따 이어서 확인하겠습니다.  (운영자에게 요청받는 형식도 추가 의견 남길 예정)

2024-07-27 03:42 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moring/question/application/QuestionService.java
> +	}
```java
question.addAnswer(answer); 
````

위의 코드는 Answer 생성자에 추가하고, 해당 메서드는 삭제해도 좋을 것 같습니다.

2024-07-27 05:11 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moring/question/application/QuestionService.java
> +	}
좋은 제안 감사합니다 👍

2024-07-29 08:24 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moring/question/application/QuestionService.java
> +			.answerContents(questionRequest.answerContents())
답변이 2개 미만, 16개 초과 시 사이즈에 대한 예외도 던져주세용

2024-07-29 08:24 UTC, nahyeon99 approved these changes

2024-07-29 08:29 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moring/question/application/QuestionService.java
> +			.answerContents(questionRequest.answerContents())
추가로, 공백, null 체크 여부도 필요할 것 같고,,  운영자용 질문과 답 전체 조회 api 와 수정 api도 필요할 것 같습니다.

2024-07-29 08:54 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moring/question/application/QuestionService.java
> +			.answerContents(questionRequest.answerContents())
```java
public record QuestionRequest(
	@Schema(description = "질문 제목", example = "오늘의 질문은?", requiredMode = REQUIRED)
	@NotBlank
	String title,

	@Schema(description = "질문 이미지 URL", example = "https://sambad.s3.ap-northeast-2.amazonaws.com/2021/10/13/1634090916_1.jpg", requiredMode = REQUIRED)
	@NotNull
	String questionImageUrl,

	@Schema(
		description = "답변 내용",
		example = "[\"답변1 예시입니다.\", \"답변2 예시입니다.\", \"답변3 예시입니다.\"]",
		requiredMode = REQUIRED
	)
	@NotNull
	List<String> answerContents

) {
}
```
예외처리 완료했습니다 👍
다만 지금 아래 코드처럼 도메인 계층에서 예외를 던지고 있는데 이 방식이 적절한지 여쭙고자 합니다.
```java
@Builder
public Question(String title, FileEntity questionImageFile, List<String> answerContents) {
	checkAnswerContents(answerContents);

	this.title = title;
	this.questionImageFile = questionImageFile;

	answerContents.forEach(answerContent -> answers.add(Answer.builder()
		.question(this)
		.content(answerContent)
		.build()));
}

private void checkAnswerContents(List<String> answerContents) {
	if (answerContents.size() < 2 || answerContents.size() > 16) {
		throw new AnswerCountOutOfRangeException();
	}
}
```

현재는 어노테이션으로 체크하고 있는데 추가적인 작업이 더 필요할까요?
운영자용 전체 조회 및 수정 api는 확실히 필요할 것 같습니다. 
하지만 1차 mvp 출시 단계에서도 해당 api가 쓰일까요?

2024-07-29 09:15 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moring/question/application/QuestionService.java
> +			.answerContents(questionRequest.answerContents())
1. 도메인 내 생성자에서 검증하는 거 좋은 것 같습니다. 👍 
다만, 2와 16은 매직 넘버이기 때문에 상수처리 해주시면 좋을 것 같아요. [참고](https://javabom.tistory.com/28)

2. null 혹은 empty 값 검증은 answerContents 컬렉션 내 값들에 대한 검증은 안되었을 거라 생각이 듭니다. forEach 구문에서 add() 할 때 검증이 추가로 필요할 듯 합니다.

3. 1차 출시 때 디쟌팀이 유저 피드백을 받을 것 같습니다. 아마 오타로 잘못들어간 질문+답은 수정 필요할 듯용??

2024-07-29 09:18 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moring/question/application/QuestionService.java
> +			.answerContents(questionRequest.answerContents())
오 좋은 피드백 감사합니당.
3번은 PR 분리해서 올리겠습니다~

2024-07-29 09:27 UTC, merged