[POSAAS-88] 로그인 기능 구현 및 kakao OAuth2 로그인 추가
depromeet/15th-team3-BE pull request #8
Opened 2024-07-13 13:37 UTC by kkjsw17

## ✔️ PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [x] 기타 사소한 수정

## 📝 개요
- Spring Security 기반 로그인 플로우를 구현합니다.
  - 자세한 처리 과정은 추후 시퀀스 다이어그램을 통해 공유드릴 예정입니다.
- Kakao OAuth2 로그인 기능을 구현합니다.
  - 추후 다른 OAuth2 서비스 추가가 가능하도록 확장성을 고려했습니다.

## ✏️ 변경 사항
- OAuth2 기반 로그인 플로우를 구현합니다.
```java
private void configureOAuth2Login(HttpSecurity http) throws Exception {
	http.oauth2Login(oauth2 ->
			oauth2.loginPage("/login")
					.userInfoEndpoint(userInfo -> userInfo.userService(defaultOAuth2UserService))
					.successHandler(authenticationSuccessHandler)
	);
	http.addFilterBefore(jwtTokenFilter, UsernamePasswordAuthenticationFilter.class);
}

private void configureExceptionHandler(HttpSecurity http) throws Exception {
	http.exceptionHandling(exceptionHandler ->
			exceptionHandler.authenticationEntryPoint(authenticationEntryPoint));
}
```
- 로그인 과정은 개략적으로 아래와 같은 플로우를 따릅니다.
  1. `DefaultOAuth2UserService`를 구현한 `OAuth2UserService`에서 OAuth2 Resource Server에서 제공한 정보를 파싱합니다.
  2. `AuthenticationSuccessHandler`를 구현한 `OAuth2LoginSuccessHandler`에서 유저 정보를 기반으로 토큰을 생성한 후, 쿠키에 토큰을 주입합니다.
- API 요청 시 인증 처리는 아래와 같은 플로우를 따릅니다.
  1. `JwtTokenFilter`에서 사용자의 **쿠키** 혹은 **헤더**에 존재하는 토큰을 파싱한 후, `UserDetails`을 주입합니다.
  2. FIlter에서 JWT 토큰 파싱에 실패한 경우 (e.g., 잘못된 토큰, 만료된 토큰 등) 401 기반 공통 오류를 반환합니다.

## 💡 코드 리뷰 시 참고 사항
- PR 크기가 너무 커져서 죄송합니다. 🙇‍♂️
  - 천천히 리뷰 부탁드립니다.

## 🔗 ISSUE 링크
- resolved [SAMBAD-88](https://www.notion.so/depromeet/Kakao-OAuth2-9b638e2a1d4e484eac572b003d743ad0?pvs=4)

2024-07-13 14:11 UTC, LeeHanEum approved these changes
리뷰가 즐거운 코드였습니다 ㅎㅎ 궁금한게 몇가지 생겨서 적어보았는데 답변 부탁드립니다!

2024-07-13 14:11 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/UserController.java
> +	public ResponseEntity<UserResponse> me(@UserId Long userId) {
메서드 명을 getUser 같은 형태가 아니라 me라고 하신 이유가 궁금합니다!

2024-07-13 14:11 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/resolver/UserId.java
> + */
UserId를 받기 위해 Argument Resolver를 사용하셨네요! 처음 보는 개념이라 궁금해서 여쭙니다 ㅎㅎ
찾아보니까 Argument Resolver란 컨트롤러에서 필요로 하는 객체를 만들고 값을 바인딩하여 전달하기 위해 사용되는 것이고,
주로 권한 체크, 파일 관리 등에서 사용하는 파라미터에 한해 사용한다고 함을 알게 되었습니다.
기준님께서는 Argument Resolver를 어떤 목적으로 사용하시는지, 특정 파라미터에만 적용시킨다면 그 기준(ㅎㅎ)은 무엇인지 알고 싶습니다!

2024-07-13 14:11 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/response/UserResponse.java
> +public record UserResponse(
자바의 record에 대해 살펴보니 다음과 같은 장점이 있었습니다.
1. 불필요한 코드를 제거할 수 있다.
2. 멤버변수는 private final로 선언된다
3. 모든 멤버변수를 인수로 가지는 생성자를 자동으로 생성해 준다
4. getter, equals, hashcode, toString과 같은 기본 메소드를 제공한다

추후 다른 도메인에 대한 DTO를 만들때에도 record를 사용할 것을 추천하시나요?
추천하신다면 저도 record로 작성해보겠습니다!

2024-07-13 14:12 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/UserController.java
> +	public ResponseEntity<UserResponse> me(@UserId Long userId) {
실수입니다! ㅋㅋㅋㅋ

2024-07-13 14:22 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/resolver/UserId.java
> + */
요 `ArgumentResolver`는 `SecurityContextHolder`에 저장된 `userId`를 어노테이션을 통해 편리하게 주입받을 수 있도록 합니다.

비즈니스 로직 수행 중 API를 호출한 유저의 ID를 꺼내와야 할 경우가 참 많은데, 그 때마다 `SecurityContextHolder` 에서 `userId`를 꺼내오는 코드를 작성하는 것 보다 어노테이션을 통해 주입받음으로써 코드의 재사용성, 가독성 측면에서 큰 이득을 볼 수 있습니다.

주로, Request body나 query param, path variable 외에 별도의 방법으로 바인딩해야 하는 데이터가 있다면 용이하게 쓸 수 있을 듯 합니다.

2024-07-13 14:23 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/response/UserResponse.java
> +public record UserResponse(
record는 불변성을 강제로 지켜준다는 점이 특장점인 것 같아요!
DTO에 적합한 친구라고 생각합니다. 추천!

2024-07-13 14:23 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/UserController.java
> +	public ResponseEntity<UserResponse> me(@UserId Long userId) {
수정 완!

2024-07-16 04:55 UTC, nahyeon99 requested changes
Security 방식이 오랜만이라, 다시 학습할 필요성을 느꼈네요 ㅠㅠ 틈틈이 추가 학습해서 놓친 부분 체크하겠습니다!

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/auth/presentation/JwtTokenFilter.java
> +	}
```java
	private void processTokenAuthentication(HttpServletRequest request, HttpServletResponse response) {
		try {
			String token = resolveTokenFromRequest(request);
			setAuthentication(request, getUserDetails(token));
		} catch (ExpiredJwtException | AuthenticationRequiredException e) {
			log.debug("Failed to authenticate", e);
			invalidateCookie(response);
		} catch (JwtException e) {
			log.warn("Failed to authenticate", e);
			invalidateCookie(response);
		} catch (Exception e) {
            // TODO: 추가 예외 작업 처리 필요
            Sentry.captureException(exception);  
            LoggingUtils.error(e);

			// log.error("Failed to authenticate", e);
			invalidateCookie(response);
		}
	}
```

Exception이 발생한 경우는 저희가 인지할 필요가 있을 것 같아서, 해당 코드를 추가해야할 것 같습니다.

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/resolver/UserIdArgumentResolver.java
> +		return Long.valueOf(authentication.getName());
authentication이 null로 들어갈 확률이 있을까요?

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/common/config/SecurityConfig.java
>  	}
ADMIN 권한이 필요한 경우도, 요 메서드에서 처리하게 될까요?

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	private FileEntity imageFile;
연관관계주인(mappedBy)이 설정되어 있지 않아요!

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	private String externalId;
요거는 무슨 필드인가요?

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	}
IDE 상에서 줄간격 선을 넘어가는 부분은 포맷팅 부탁드립니다!

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/user/infrastructure/UserRepositoryImpl.java
>  	}
@Override 가 생략되어 있어요.

2024-07-16 04:55 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/auth/application/dto/AuthAttributes.java
> +	}
구현체가 아닌 인터페이스에 생성자를 두신 이유가 있을까요? 인터페이스에 둔다면, 네이밍을 kakaoOf 같이 카카오 방식 생성자임을 드러내는 것이 좋을 것 같습니다!

2024-07-16 08:15 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/infrastructure/UserRepositoryImpl.java
>  	}
오 넵 확인 감사드립니다.

2024-07-16 08:15 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	}
넵!

2024-07-16 08:17 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	private String externalId;
ERD에 적어두었으니 확인 부탁드립니다 👍
어디에 사용되는지는 @see 로 달아놓을게요.

2024-07-16 08:17 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	private FileEntity imageFile;
아! 실무에서 연관관계 아예 안쓰다보니 가물가물 하네요 ㅎㅎ;; 수정하겠습니다.

2024-07-16 08:18 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/common/config/SecurityConfig.java
>  	}
깊게는 생각 안해봤는데요. 단순 API 호출에 대한 제어는 여기서 하지 않을까 싶습니다.
더 복잡한 권한 별 관리 요구사항이 생기면 어노테이션으로 뺄 것 같아요.

2024-07-16 08:19 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/user/presentation/resolver/UserIdArgumentResolver.java
> +		return Long.valueOf(authentication.getName());
있겠네요. null 체크 하겠습니다 ㅎㅎ

2024-07-16 08:19 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/auth/presentation/JwtTokenFilter.java
> +	}
넹 추가해둘게요.

2024-07-16 08:19 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/auth/application/dto/AuthAttributes.java
> +	}
요거 왜 이렇게 짰더라! 퇴근하고 좀 더 확인해보고 댓글 달아두겠습니다.

2024-07-16 08:22 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/common/config/SecurityConfig.java
>  	}
아 그렇군요, 확인 감사합니다 😊

2024-07-16 08:23 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	private String externalId;
오 확인했습니다. 구체적으로 작성해주셨군요 😅👍

2024-07-16 08:23 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/user/domain/User.java
> +	private FileEntity imageFile;
럴수럴수이럴수가

2024-07-16 15:47 UTC, nahyeon99 approved these changes

2024-07-16 16:32 UTC, merged