[SAMBAD-95] NCP Object Storage를 사용한 파일 업로드 기능
depromeet/15th-team3-BE pull request #9
Opened 2024-07-14 18:02 UTC by LeeHanEum

### 📍 [SAMBAD-95] NCP Object Storage를 사용한 파일 업로드 기능

## ✔️ PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## 📝 개요
- NCP Object Storage를 사용하여 파일 업로드, 다운로드, 조회 기능을 구현합니다.
- 파일 정보를 DB에 저장합니다.
```java
@Override
	public String upload(MultipartFile multipartFile, String logicalName) throws IOException {
		try {
			File uploadFile = convert(multipartFile)
				.orElseThrow(() -> new IllegalArgumentException("MultipartFile -> File convert failed."));
			amazonS3.putObject(
				new PutObjectRequest(bucketName, logicalName, uploadFile)
					.withCannedAcl(CannedAccessControlList.PublicRead)
			);
			removeNewFile(uploadFile);
		} catch (FileUploadErrorException e) {
			throw new FileUploadErrorException();
		}
		return amazonS3.getUrl(bucketName, logicalName).toString();
	}
```

## ✏️ 변경 사항
### [커밋타이틀-1](커밋링크)
  
  - description-1
  - description-2

### [커밋타이틀-2](커밋링크)

- description-1
- description-2

## 💡 코드 리뷰 시 참고 사항
  - Service, Repository 등 각 계층이 올바른 패키지 구조로 이루어져 있는지 확인 부탁드립니다.

## 🔗 ISSUE 링크
- resolved [SAMBAD-이슈번호]()

2024-07-16 16:58 UTC, kkjsw17 reviewed
리뷰 남겼습니다~!

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/common/config/ObjectStorageConfig.java
> +	private String endpoint;
null check 가능하면 좋겠는데, `ConfigurationProperties` 사용은 어떠신가요??

```java
@Validated
@ConfigurationProperties(prefix = "cloud.ncp.object-storage")
public record ObjectStorageProperties(
        @NotNull String credentialsAccessKey,
        @NotNull String credentialsSecretKey,
        @NotNull String regionStatic,
        @NotNull String endpoint) {
}
```
이런 느낌s로 가능합니다.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/common/config/SecurityConfig.java
> +		"/api/v1/object-storage/**"
`/api/v1/object-storage/**` 빼는게 좋을듯요!

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +@RequestMapping("/api/v1/object-storage")
논의한 대로 `/api` 빼고 representation `files`로 가는게 좋아보여요!

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +		@RequestPart(value = "fileName") String fileName
파일 삭제는 `fileId` 기반이 되어야 할 것 같습니다.
그리고, 파일 삭제 기능은 요구사항에 일단 없어서 API는 없어도 될 것 같아요.
`FileService`에는 남겨두어도 될 듯 하구요

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/application/FileService.java
> +	}
파일 삭제는 `fileId` 기반이 되어야 할 것 같습니다.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/application/FileService.java
> +	private boolean isExistFile(String logicalName) {
`isExistFile` -> `isNotExistFile` 이 되어야 할 것 같아요.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/application/FileService.java
> +		if(isExistFile(logicalName)) {
`Cmd + Opt + L` 통해서 포맷팅 부탁드리겠습니다. `if`랑 `(` 사이는 띄워쓰는게 좋을 것 같아요!

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +	@GetMapping(path = "/download/{fileName}")
fileId 기반이 되어야 할 것 같아요.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +		httpHeaders.setContentType(MediaType.IMAGE_JPEG);
JPEG가 아닐 수도 있는 점을 고려해야 할 것 같아요.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +	public ResponseEntity<byte[]> downloadFile(
파일은 CDN 혹은 스토리지 통해 접근할 것이기 때문에, 다운로드 API가 별도로 필요하지 않습니다.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +		@RequestPart(value = "file", required = false) MultipartFile multipartFile
multipart에 파일 명 포함되는 걸로 알고 있습니다.
fileName 따로 받지 않고 multipart에서 뽑아서 사용하는 걸로 변경해도 될 것 같습니다.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/infrastructure/ObjectStorageFileUploader.java
> +	}
새로 구현해야 하는거 아니면, 없어도 될 것 같습니다.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/infrastructure/ObjectStorageFileUploader.java
> +	}
포맷팅 필요해보입니다.

2024-07-16 16:58 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/response/FileResponse.java
> +}
요거 쓰이나요?

2024-07-16 17:11 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/common/config/ObjectStorageConfig.java
> +	private String endpoint;
오 좋은 제안 감사합니다. 적용해보겠습니다.

2024-07-16 17:12 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/common/config/SecurityConfig.java
> +		"/api/v1/object-storage/**"
넵 제거하겠습니다

2024-07-16 17:12 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +@RequestMapping("/api/v1/object-storage")
넵 수정해놓을께요!

2024-07-16 17:12 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +		@RequestPart(value = "fileName") String fileName
fileId 기반으로 조회하는 방향으로 수정하겠습니다!

2024-07-16 17:13 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/application/FileService.java
> +	private boolean isExistFile(String logicalName) {
앗 실수네요 ㅎㅎ 감사합니다!

2024-07-16 17:13 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/application/FileService.java
> +		if(isExistFile(logicalName)) {
넵 감사합니다!

2024-07-16 17:14 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +		httpHeaders.setContentType(MediaType.IMAGE_JPEG);
아 이 부분도 놓쳤네요. 감사합니다!

2024-07-16 17:15 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +	public ResponseEntity<byte[]> downloadFile(
다운로드 api는 제거하겠습니다

2024-07-16 17:15 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +		@RequestPart(value = "file", required = false) MultipartFile multipartFile
multipart에서 뽑아서 사용하는 방식으로 변경하겠습니다

2024-07-16 17:16 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/response/FileResponse.java
> +}
다운로드 api 대신에 조회 api로 변경할 때 사용하겠습니다.

2024-07-16 18:19 UTC, nahyeon99 requested changes
화이팅~~💪

2024-07-16 18:19 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +}
파일 업로드 및 삭제 엔드포인트가 어떤 경우에 사용하게 될까요? 운영자가 릴레이 질문 이미지 업로드 할 때, 엔드포인트로 요청할 의도셨을까요?

2024-07-16 18:19 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +public class ObjectStorageController {
컨트롤러 네이밍은 FileController가 좋을 것 같습니다. 하위 구현체가 상위 레벨인 컨트롤러에 드러낼 필요가 없는 느낌s?

2024-07-16 18:19 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/exception/FileExceptionCode.java
> +	FILE_DELETE_ERROR(INTERNAL_SERVER_ERROR, "파일 삭제 중 에러가 발생했습니다.");
센트리 혹은 AOP 로깅 방식에는 호출된 메서드가 추적이 가능해서, FILE_UPLOAD_ERROR, FILE_DELETE_ERROR 는 OBJECTSTORAGE_SERVER_ERROR로 퉁치는 방향으로 생각했었는데요. 해당 방식 선택한 이유가 궁금합니다! 

그리고 ExceptionCode 관련 enum 파일에서는, httpStatus 기준으로 개행 나누는 컨벤션 어떠신가용?

2024-07-17 08:24 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +}
네 맞습니다. 말씀하신대로 운영자가 스웨거를 사용해서 파일 업로드 및 삭제를 할 수 있도록 하기 위함이었습니다. 해당 api 제거하지 않는게 좋을까요?

2024-07-17 08:24 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +public class ObjectStorageController {
네이밍도 수정하겠습니다^^

2024-07-17 08:26 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/exception/FileExceptionCode.java
> +	FILE_DELETE_ERROR(INTERNAL_SERVER_ERROR, "파일 삭제 중 에러가 발생했습니다.");
예외를 세분화하려는 의도였습니다. 제거 여부 알려주시면 감사하겠습니다.

2024-07-17 08:29 UTC, kkjsw17 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +}
지금 단계에선 제거하는게 좋을 것 같습니다.
운영 인원만 접근할 수 있는 API가 아닐 뿐더러, 누구든지 자신의 파일 뿐만 아니라 서버에 존재하는 모든 파일을 삭제할 수 있는 형태여서 많은 보강이 필요해 보입니다.
서비스 코드는 남겨두고, 추후 요구사항 생기면 다시 고려해보는게 좋을 것 같습니다 👍

2024-07-17 08:51 UTC, nahyeon99 commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/exception/FileExceptionCode.java
> +	FILE_DELETE_ERROR(INTERNAL_SERVER_ERROR, "파일 삭제 중 에러가 발생했습니다.");
OBJECTSTORAGE_SERVER_ERROR를 던지는 방향으로 일단 진행하는 것이 좋을 것 같습니다!

2024-07-17 09:11 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/ObjectStorageController.java
> +}
네 말씀하신대로 서비스 코드는 두고 api는 제거하겠습니다!

2024-07-17 09:12 UTC, LeeHanEum commented on src/main/java/org/depromeet/sambad/moyeo/file/presentation/exception/FileExceptionCode.java
> +	FILE_DELETE_ERROR(INTERNAL_SERVER_ERROR, "파일 삭제 중 에러가 발생했습니다.");
네 그렇게 수정하겠습니다!

2024-07-18 03:14 UTC, nahyeon99 approved these changes

2024-07-18 17:47 UTC, closed without merging